// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/availability.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailablilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablilityRequest) Reset() {
	*x = AvailablilityRequest{}
	mi := &file_proto_availability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablilityRequest) ProtoMessage() {}

func (x *AvailablilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablilityRequest.ProtoReflect.Descriptor instead.
func (*AvailablilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_availability_proto_rawDescGZIP(), []int{0}
}

func (x *AvailablilityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailablilityRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AvailablilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availablility bool                   `protobuf:"varint,1,opt,name=availablility,proto3" json:"availablility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablilityResponse) Reset() {
	*x = AvailablilityResponse{}
	mi := &file_proto_availability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablilityResponse) ProtoMessage() {}

func (x *AvailablilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablilityResponse.ProtoReflect.Descriptor instead.
func (*AvailablilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_availability_proto_rawDescGZIP(), []int{1}
}

func (x *AvailablilityResponse) GetAvailablility() bool {
	if x != nil {
		return x.Availablility
	}
	return false
}

type ReserveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderProducts []*OrderProduct        `protobuf:"bytes,1,rep,name=orderProducts,proto3" json:"orderProducts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveOrderRequest) Reset() {
	*x = ReserveOrderRequest{}
	mi := &file_proto_availability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOrderRequest) ProtoMessage() {}

func (x *ReserveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOrderRequest.ProtoReflect.Descriptor instead.
func (*ReserveOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_availability_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveOrderRequest) GetOrderProducts() []*OrderProduct {
	if x != nil {
		return x.OrderProducts
	}
	return nil
}

type OrderProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProduct) Reset() {
	*x = OrderProduct{}
	mi := &file_proto_availability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProduct) ProtoMessage() {}

func (x *OrderProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProduct.ProtoReflect.Descriptor instead.
func (*OrderProduct) Descriptor() ([]byte, []int) {
	return file_proto_availability_proto_rawDescGZIP(), []int{3}
}

func (x *OrderProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ReserveOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsReserved     bool                   `protobuf:"varint,1,opt,name=isReserved,proto3" json:"isReserved,omitempty"`
	Price          float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	ProductsSeller []*ProductSeller       `protobuf:"bytes,3,rep,name=productsSeller,proto3" json:"productsSeller,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveOrderResponse) Reset() {
	*x = ReserveOrderResponse{}
	mi := &file_proto_availability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOrderResponse) ProtoMessage() {}

func (x *ReserveOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOrderResponse.ProtoReflect.Descriptor instead.
func (*ReserveOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_availability_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveOrderResponse) GetIsReserved() bool {
	if x != nil {
		return x.IsReserved
	}
	return false
}

func (x *ReserveOrderResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ReserveOrderResponse) GetProductsSeller() []*ProductSeller {
	if x != nil {
		return x.ProductsSeller
	}
	return nil
}

type ProductSeller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	SellerId      string                 `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSeller) Reset() {
	*x = ProductSeller{}
	mi := &file_proto_availability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSeller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSeller) ProtoMessage() {}

func (x *ProductSeller) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSeller.ProtoReflect.Descriptor instead.
func (*ProductSeller) Descriptor() ([]byte, []int) {
	return file_proto_availability_proto_rawDescGZIP(), []int{5}
}

func (x *ProductSeller) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductSeller) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductSeller) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

var File_proto_availability_proto protoreflect.FileDescriptor

const file_proto_availability_proto_rawDesc = "" +
	"\n" +
	"\x18proto/availability.proto\x12\x05proto\"K\n" +
	"\x14availablilityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"=\n" +
	"\x15availablilityResponse\x12$\n" +
	"\ravailablility\x18\x01 \x01(\bR\ravailablility\"P\n" +
	"\x13ReserveOrderRequest\x129\n" +
	"\rorderProducts\x18\x01 \x03(\v2\x13.proto.orderProductR\rorderProducts\"C\n" +
	"\forderProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"\x8a\x01\n" +
	"\x14ReserveOrderResponse\x12\x1e\n" +
	"\n" +
	"isReserved\x18\x01 \x01(\bR\n" +
	"isReserved\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12<\n" +
	"\x0eproductsSeller\x18\x03 \x03(\v2\x14.proto.productSellerR\x0eproductsSeller\"a\n" +
	"\rproductSeller\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\tR\bsellerId2b\n" +
	"\x14availablilityService\x12J\n" +
	"\visAvailable\x12\x1b.proto.availablilityRequest\x1a\x1c.proto.availablilityResponse\"\x002Y\n" +
	"\fOrderService\x12I\n" +
	"\fReserveOrder\x12\x1a.proto.ReserveOrderRequest\x1a\x1b.proto.ReserveOrderResponse\"\x00B4Z2github.com/Gergenus/commerce/product-service/protob\x06proto3"

var (
	file_proto_availability_proto_rawDescOnce sync.Once
	file_proto_availability_proto_rawDescData []byte
)

func file_proto_availability_proto_rawDescGZIP() []byte {
	file_proto_availability_proto_rawDescOnce.Do(func() {
		file_proto_availability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_availability_proto_rawDesc), len(file_proto_availability_proto_rawDesc)))
	})
	return file_proto_availability_proto_rawDescData
}

var file_proto_availability_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_availability_proto_goTypes = []any{
	(*AvailablilityRequest)(nil),  // 0: proto.availablilityRequest
	(*AvailablilityResponse)(nil), // 1: proto.availablilityResponse
	(*ReserveOrderRequest)(nil),   // 2: proto.ReserveOrderRequest
	(*OrderProduct)(nil),          // 3: proto.orderProduct
	(*ReserveOrderResponse)(nil),  // 4: proto.ReserveOrderResponse
	(*ProductSeller)(nil),         // 5: proto.productSeller
}
var file_proto_availability_proto_depIdxs = []int32{
	3, // 0: proto.ReserveOrderRequest.orderProducts:type_name -> proto.orderProduct
	5, // 1: proto.ReserveOrderResponse.productsSeller:type_name -> proto.productSeller
	0, // 2: proto.availablilityService.isAvailable:input_type -> proto.availablilityRequest
	2, // 3: proto.OrderService.ReserveOrder:input_type -> proto.ReserveOrderRequest
	1, // 4: proto.availablilityService.isAvailable:output_type -> proto.availablilityResponse
	4, // 5: proto.OrderService.ReserveOrder:output_type -> proto.ReserveOrderResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_availability_proto_init() }
func file_proto_availability_proto_init() {
	if File_proto_availability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_availability_proto_rawDesc), len(file_proto_availability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_availability_proto_goTypes,
		DependencyIndexes: file_proto_availability_proto_depIdxs,
		MessageInfos:      file_proto_availability_proto_msgTypes,
	}.Build()
	File_proto_availability_proto = out.File
	file_proto_availability_proto_goTypes = nil
	file_proto_availability_proto_depIdxs = nil
}
