// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availablility bool                   `protobuf:"varint,1,opt,name=availablility,proto3" json:"availablility,omitempty"`
	OrderProducts []*OrderProduct        `protobuf:"bytes,2,rep,name=orderProducts,proto3" json:"orderProducts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetCartResponse) GetAvailablility() bool {
	if x != nil {
		return x.Availablility
	}
	return false
}

func (x *GetCartResponse) GetOrderProducts() []*OrderProduct {
	if x != nil {
		return x.OrderProducts
	}
	return nil
}

type OrderProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProduct) Reset() {
	*x = OrderProduct{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProduct) ProtoMessage() {}

func (x *OrderProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProduct.ProtoReflect.Descriptor instead.
func (*OrderProduct) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ReserveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderProducts []*OrderProduct        `protobuf:"bytes,1,rep,name=orderProducts,proto3" json:"orderProducts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveOrderRequest) Reset() {
	*x = ReserveOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOrderRequest) ProtoMessage() {}

func (x *ReserveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOrderRequest.ProtoReflect.Descriptor instead.
func (*ReserveOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveOrderRequest) GetOrderProducts() []*OrderProduct {
	if x != nil {
		return x.OrderProducts
	}
	return nil
}

type ReserveOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsReserved     bool                   `protobuf:"varint,1,opt,name=isReserved,proto3" json:"isReserved,omitempty"`
	Price          float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	ProductsSeller []*ProductSeller       `protobuf:"bytes,3,rep,name=productsSeller,proto3" json:"productsSeller,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveOrderResponse) Reset() {
	*x = ReserveOrderResponse{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOrderResponse) ProtoMessage() {}

func (x *ReserveOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOrderResponse.ProtoReflect.Descriptor instead.
func (*ReserveOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveOrderResponse) GetIsReserved() bool {
	if x != nil {
		return x.IsReserved
	}
	return false
}

func (x *ReserveOrderResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ReserveOrderResponse) GetProductsSeller() []*ProductSeller {
	if x != nil {
		return x.ProductsSeller
	}
	return nil
}

type ProductSeller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	SellerId      string                 `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSeller) Reset() {
	*x = ProductSeller{}
	mi := &file_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSeller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSeller) ProtoMessage() {}

func (x *ProductSeller) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSeller.ProtoReflect.Descriptor instead.
func (*ProductSeller) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *ProductSeller) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductSeller) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductSeller) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x05proto\")\n" +
	"\x0egetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"r\n" +
	"\x0fgetCartResponse\x12$\n" +
	"\ravailablility\x18\x01 \x01(\bR\ravailablility\x129\n" +
	"\rorderProducts\x18\x02 \x03(\v2\x13.proto.orderProductR\rorderProducts\"C\n" +
	"\forderProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"P\n" +
	"\x13ReserveOrderRequest\x129\n" +
	"\rorderProducts\x18\x01 \x03(\v2\x13.proto.orderProductR\rorderProducts\"\x8a\x01\n" +
	"\x14ReserveOrderResponse\x12\x1e\n" +
	"\n" +
	"isReserved\x18\x01 \x01(\bR\n" +
	"isReserved\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12<\n" +
	"\x0eproductsSeller\x18\x03 \x03(\v2\x14.proto.productSellerR\x0eproductsSeller\"a\n" +
	"\rproductSeller\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\tR\bsellerId2\x95\x01\n" +
	"\fOrderService\x12:\n" +
	"\aGetCart\x12\x15.proto.getCartRequest\x1a\x16.proto.getCartResponse\"\x00\x12I\n" +
	"\fReserveOrder\x12\x1a.proto.ReserveOrderRequest\x1a\x1b.proto.ReserveOrderResponse\"\x00B2Z0github.com/Gergenus/commerce/order-service/protob\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_order_proto_goTypes = []any{
	(*GetCartRequest)(nil),       // 0: proto.getCartRequest
	(*GetCartResponse)(nil),      // 1: proto.getCartResponse
	(*OrderProduct)(nil),         // 2: proto.orderProduct
	(*ReserveOrderRequest)(nil),  // 3: proto.ReserveOrderRequest
	(*ReserveOrderResponse)(nil), // 4: proto.ReserveOrderResponse
	(*ProductSeller)(nil),        // 5: proto.productSeller
}
var file_proto_order_proto_depIdxs = []int32{
	2, // 0: proto.getCartResponse.orderProducts:type_name -> proto.orderProduct
	2, // 1: proto.ReserveOrderRequest.orderProducts:type_name -> proto.orderProduct
	5, // 2: proto.ReserveOrderResponse.productsSeller:type_name -> proto.productSeller
	0, // 3: proto.OrderService.GetCart:input_type -> proto.getCartRequest
	3, // 4: proto.OrderService.ReserveOrder:input_type -> proto.ReserveOrderRequest
	1, // 5: proto.OrderService.GetCart:output_type -> proto.getCartResponse
	4, // 6: proto.OrderService.ReserveOrder:output_type -> proto.ReserveOrderResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
