// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/availablility.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailablilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablilityRequest) Reset() {
	*x = AvailablilityRequest{}
	mi := &file_proto_availablility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablilityRequest) ProtoMessage() {}

func (x *AvailablilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availablility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablilityRequest.ProtoReflect.Descriptor instead.
func (*AvailablilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_availablility_proto_rawDescGZIP(), []int{0}
}

func (x *AvailablilityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailablilityRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AvailablilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availablility bool                   `protobuf:"varint,1,opt,name=availablility,proto3" json:"availablility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablilityResponse) Reset() {
	*x = AvailablilityResponse{}
	mi := &file_proto_availablility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablilityResponse) ProtoMessage() {}

func (x *AvailablilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availablility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablilityResponse.ProtoReflect.Descriptor instead.
func (*AvailablilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_availablility_proto_rawDescGZIP(), []int{1}
}

func (x *AvailablilityResponse) GetAvailablility() bool {
	if x != nil {
		return x.Availablility
	}
	return false
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_proto_availablility_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availablility_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_availablility_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availablility bool                   `protobuf:"varint,1,opt,name=availablility,proto3" json:"availablility,omitempty"`
	OrderProducts []*OrderProduct        `protobuf:"bytes,2,rep,name=orderProducts,proto3" json:"orderProducts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_proto_availablility_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availablility_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_availablility_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartResponse) GetAvailablility() bool {
	if x != nil {
		return x.Availablility
	}
	return false
}

func (x *GetCartResponse) GetOrderProducts() []*OrderProduct {
	if x != nil {
		return x.OrderProducts
	}
	return nil
}

type OrderProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProduct) Reset() {
	*x = OrderProduct{}
	mi := &file_proto_availablility_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProduct) ProtoMessage() {}

func (x *OrderProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_availablility_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProduct.ProtoReflect.Descriptor instead.
func (*OrderProduct) Descriptor() ([]byte, []int) {
	return file_proto_availablility_proto_rawDescGZIP(), []int{4}
}

func (x *OrderProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_proto_availablility_proto protoreflect.FileDescriptor

const file_proto_availablility_proto_rawDesc = "" +
	"\n" +
	"\x19proto/availablility.proto\x12\x05proto\"K\n" +
	"\x14availablilityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"=\n" +
	"\x15availablilityResponse\x12$\n" +
	"\ravailablility\x18\x01 \x01(\bR\ravailablility\")\n" +
	"\x0egetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"r\n" +
	"\x0fgetCartResponse\x12$\n" +
	"\ravailablility\x18\x01 \x01(\bR\ravailablility\x129\n" +
	"\rorderProducts\x18\x02 \x03(\v2\x13.proto.orderProductR\rorderProducts\"C\n" +
	"\forderProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock2b\n" +
	"\x14availablilityService\x12J\n" +
	"\visAvailable\x12\x1b.proto.availablilityRequest\x1a\x1c.proto.availablilityResponse\"\x002J\n" +
	"\fOrderService\x12:\n" +
	"\aGetCart\x12\x15.proto.getCartRequest\x1a\x16.proto.getCartResponse\"\x00B1Z/github.com/Gergenus/commerce/cart-service/protob\x06proto3"

var (
	file_proto_availablility_proto_rawDescOnce sync.Once
	file_proto_availablility_proto_rawDescData []byte
)

func file_proto_availablility_proto_rawDescGZIP() []byte {
	file_proto_availablility_proto_rawDescOnce.Do(func() {
		file_proto_availablility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_availablility_proto_rawDesc), len(file_proto_availablility_proto_rawDesc)))
	})
	return file_proto_availablility_proto_rawDescData
}

var file_proto_availablility_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_availablility_proto_goTypes = []any{
	(*AvailablilityRequest)(nil),  // 0: proto.availablilityRequest
	(*AvailablilityResponse)(nil), // 1: proto.availablilityResponse
	(*GetCartRequest)(nil),        // 2: proto.getCartRequest
	(*GetCartResponse)(nil),       // 3: proto.getCartResponse
	(*OrderProduct)(nil),          // 4: proto.orderProduct
}
var file_proto_availablility_proto_depIdxs = []int32{
	4, // 0: proto.getCartResponse.orderProducts:type_name -> proto.orderProduct
	0, // 1: proto.availablilityService.isAvailable:input_type -> proto.availablilityRequest
	2, // 2: proto.OrderService.GetCart:input_type -> proto.getCartRequest
	1, // 3: proto.availablilityService.isAvailable:output_type -> proto.availablilityResponse
	3, // 4: proto.OrderService.GetCart:output_type -> proto.getCartResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_availablility_proto_init() }
func file_proto_availablility_proto_init() {
	if File_proto_availablility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_availablility_proto_rawDesc), len(file_proto_availablility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_availablility_proto_goTypes,
		DependencyIndexes: file_proto_availablility_proto_depIdxs,
		MessageInfos:      file_proto_availablility_proto_msgTypes,
	}.Build()
	File_proto_availablility_proto = out.File
	file_proto_availablility_proto_goTypes = nil
	file_proto_availablility_proto_depIdxs = nil
}
